### ISSUE TITLE
failed when run the command "roslaunch ford_mondeo carla_simulation.launch "

### ISSUE THREAD

**Issue by sheepwxy** [MrMushroom/CarlaScenarioLoader#2]
hello, your job is very valuable. 

when I run the command "roslaunch ford_mondeo carla_simulation.launch ",it failed.  what is the meaning of this command, i can not also the file  "carla_simulation.launch" and "ford_mondeo"

please help me.

**Comment by MrMushroom** [comment]
Hi!

Thank you for pointing out this missleading instruction! This command stands for the ROS algorithms which are under test.

roslaunch is the command to start ROS environments.

ford_mondeo is the project containing the algorithms for the ford_mondeo we use to test as software in the loop. This part should be exchanged by the algorithms of the car you want to test. The algorithms simply have to use dataspeed drive-by-wire messages for communication.

carla_simulation.launch is the ROS launch file of the ford_mondeo project which starts the algorithms of our car, as well es some ROS visualization debug stuff.

All in all, you should adapt this line to fit your ROS environment, i.e. the car you want to test. I will change the descriptive part of the  InstallAll.sh accordingly.

HTH!

**Comment by sheepwxy** [comment]
> 
> 
> Hi!
> 
> Thank you for pointing out this missleading instruction! This command stands for the ROS algorithms which are under test.
> 
> roslaunch is the command to start ROS environments.
> 
> ford_mondeo is the project containing the algorithms for the ford_mondeo we use to test as software in the loop. This part should be exchanged by the algorithms of the car you want to test. The algorithms simply have to use dataspeed drive-by-wire messages for communication.
> 
> carla_simulation.launch is the ROS launch file of the ford_mondeo project which starts the algorithms of our car, as well es some ROS visualization debug stuff.
> 
> All in all, you should adapt this line to fit your ROS environment, i.e. the car you want to test. I will change the descriptive part of the InstallAll.sh accordingly.
> 
> HTH!

Thanks for your replying！

And in your thesis，I noticed the ROS project “https://bitbucket.org/DataspeedInc/dbw_mkz_ros”.
Is this the ROS project which you used ? And can you shows the related code about the Ros Project you used?  Because now, my core concerns is the autonomous driving testing and the OpensCENARIO, and I have no proper  algorithms to test.   It also can help me a lot for learning how to adapt new project.

thanks a lot!

**Comment by MrMushroom** [comment]
> And in your thesis，I noticed the ROS project “[https://bitbucket.org/DataspeedInc/dbw_mkz_ros”](https://bitbucket.org/DataspeedInc/dbw_mkz_ros%E2%80%9D).
> Is this the ROS project which you used ? And can you shows the related code about the Ros Project you used? 

Yes, this project contains the drive-by-wire (dbw) messages which are used by our software and which are also used within our demonstrator car. Unfortunately I can't provide you with our ADS algorithms ;)

> Because now, my core concerns is the autonomous driving testing and the OpensCENARIO, and I have no proper algorithms to test. It also can help me a lot for learning how to adapt new project.

However, I can recommend (https://github.com/udacity/CarND-Capstone), with this project you can create a basic lane following ADS. The dbw_node already uses the dbw_mkz messages of DataSpeed.

HTH!

**Comment by sheepwxy** [comment]
thanks for your help！

**Comment by sheepwxy** [comment]
> 
> 
> > And in your thesis，I noticed the ROS project “[https://bitbucket.org/DataspeedInc/dbw_mkz_ros”](https://bitbucket.org/DataspeedInc/dbw_mkz_ros%E2%80%9D).
> > Is this the ROS project which you used ? And can you shows the related code about the Ros Project you used?
> 
> Yes, this project contains the drive-by-wire (dbw) messages which are used by our software and which are also used within our demonstrator car. Unfortunately I can't provide you with our ADS algorithms ;)
> 
> > Because now, my core concerns is the autonomous driving testing and the OpensCENARIO, and I have no proper algorithms to test. It also can help me a lot for learning how to adapt new project.
> 
> However, I can recommend (https://github.com/udacity/CarND-Capstone), with this project you can create a basic lane following ADS. The dbw_node already uses the dbw_mkz messages of DataSpeed.
> 
> HTH!

thanks for your help！

**Comment by sheepwxy** [comment]
thanks for your help！
