### ISSUE TITLE
A small error in "OpenCarla.sh"

### ISSUE THREAD

**Issue by sheepwxy** [MrMushroom/CarlaScenarioLoader#3]
hello,there is a small mistake in the file " OpenCarla.sh"

for the Carla0.9.5, the UE4 version is 4.21. And you should change the sencond line as “UE4_ROOT=~/UnrealEngine_4.21 make launch-only”

**Comment by MrMushroom** [comment]
Thank you!

Didn't use that file for a while ;)

--- FIXED ---
