### ISSUE TITLE
The installation issue with this CarlaScenarioLoader plugin

### ISSUE THREAD

**Issue by HoneyDarling2468** [MrMushroom/CarlaScenarioLoader#6]
Hi @MrMushroom，I have three questions to ask you.
Firstly, when I finish running the InstallAll.sh file, it prompts me that the installation is complete. But when I run _./OpenCarla.sh_, the system prompts "Make: * * * There are no rules to create the target" launch only ". Stop." Then I cannot proceed to the next step.
Secondly, am I continuing to follow the steps in the picture? I have read your journal papers and master's theses, and I have found that I do not know how to run your project.
Thirdly, when I run _./test.sh_ directly, the system prompts:
Traceback (most recent call last):
File "scenario_loader. py", line 10, in<module>
Import prctl
"ModuleNotFoundError: No module named 'prctl'"
![Uploading issue.png…]()

**Comment by HoneyDarling2468** [comment]
![Uploading issue.png…]()

**Comment by MrMushroom** [comment]
Heyho!
It's nice to see that my code may be helpful to someone.

Right away. I wrote the code a really long time ago. For running scenarios with Carla, I also highly recommend using the [Carla Scenario Runner](https://carla-scenariorunner.readthedocs.io/en/latest/). We had 2-3 telcos with the development team via Discord. They then looked at my code and may or may not have adapted things. In general, their development team is much bigger than I was alone.

Towards your current issue:
- InstallAll.sh is designed to install all requirements. It is also designed as documentation. These parts must run through cleanly, or else it won't work. However, the only thing that needs to be checked by hand is the OS version. I ran the code with Ubuntu 16.04 LTS.
- OpenCarla.sh starts the Carla environment. It seems that Carla was not correctly installed. Please feel free to take a look at that.
- test.sh runs the tests via the scenario_loader.py file. The call parameters are listed in scenario_loader.py line 15-22. "The files test.sh uses them, as I used them on my machine. you may want to configure that."
- as for the "prctl" error, I am quite sure the InstallAll.sh (lines 18-19) did not work as intended. 

Summarizing, I think that your OS version could be off. I.e., it is not Ubuntu 16.04 LTS.

BTW: I could not see your picture. It seems it was not successfully uploaded.

HTH and BR

**Comment by HoneyDarling2468** [comment]
Okay, thank you very much for replying to me. It made me feel like I saw hope when I was lost.

- As you wish, I will try using the _Carla Scenario Runner_ software recommended by you to run the Carla scenario. Thank you very much for guiding me in the direction.
- Based on your answer, I may be aware of my question. Indeed, my version is Ubuntu 18.04, which may be where the problem lies.
- Finally, I have one more question to ask you. Now, I want to generate autonomous driving simulation test scenarios through programmatic means, including some road network structures, traffic sign facilities, weather conditions, and some traffic dynamic participants. I am trying to use OpenSCENARIO syntax to generate. xodr files, then import them into Carla for scene generation, and finally find a way to package this process in software to form a simple exe file. May I ask if my process is reasonable? Or do you recommend a toolchain to achieve my goal of programmatic scene generation?

**Comment by MrMushroom** [comment]
Happy to help! I hope you will soon find a path to walk :)

- Sounds good ;)
- Yeah, this could be the issue. Version changes cause lots of trouble for non-precompiled software.
- Yes, it sounds like a reasonable approach. You may find smaller tools depending on how detailed and complex your scenarios are.

A quick Google search for "generate openscenario files" found me:
- https://github.com/pyoscx/scenariogeneration
- https://github.com/EFS-OpenSource/OSC-Generator

Btw, if you are using CARLA:
- you should check out their dev wiki. There are some helpful in-progress things: https://carla.readthedocs.io/en/latest/tuto_G_openstreetmap/
- you may also join their Discord (linked on the homepage and in docs). The community is really helpful!

**Comment by HoneyDarling2468** [comment]
Thank you very much for helping me.
Through your guidance, I have identified the problem. I will try the method you recommended, thank you again for your patient answer.
Best wishes.
